logger:
  level: DEBUG #INFO
  output:
    - stdout

connectors:
  postgres:
    PG1:
      driver: postgres
      dsn: "host=127.0.0.1 port=5432 user=todolist password=secretpwd dbname=todolist sslmode=disable"

controllers:
  task_controller:
    task_dao: 
      type: TaskPostgresDAO
      connector: pg1

ginrouters:
  addr: ""
  port: 8080
  gin_mode: debug
  shutdown_timeout: 5