logger:
  level: DEBUG #INFO
  output:
    - stdout

connectors:
  mongo:
    md1:
        db: todolist
        host: 127.0.0.1
        port: 27017
        username: todolist
        password: secretpwd
        timeout: 10

  #postgres:
  #  pg1:
  #    driver: postgres
  #    dsn: "host=127.0.0.1 port=5432 user=todolist password=secretpwd dbname=todolist sslmode=disable"

controllers:
  task_controller:
    task_dao: 
      type: TaskMongoDAO
      connector: md1

ginrouters:
  addr: ""
  port: 8080
  gin_mode: debug
  shutdown_timeout: 5
